# the containing folder (/path/to/) should already exist
# the same db file should be configured for the jobber-site repo
db_file = '/path/to/db.sqlite'

# https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.2-GGUF
model_file = '/path/to/mistral-7b-instruct-v0.2.Q8_0.gguf'

# llama-cpp-python needs to be built from scratch for gpu-support to work (see requirements.txt)
use_gpu = false

# mistral 7b uses ~6GB VRAM per worker
num_workers = 1

# Skills in a job posting are detected using case-insensitive regex patterns
[[skills]]
name = 'Python'
patts = ['[^\w]python[^\w]']

[[skills]]
name = 'C++'
patts = ['[^\w]c\+\+[^\w]']

# Duties in a job posting are detected using a yes-or-no question fed to an LLM
[[duties]]
name = 'On-call'
prompt = 'Does the position involve a support / on-call rotation?'

[[duties]]
name = 'Travel'
prompt = 'Does the position require occasional travel?'
